[package]
name = "wry_disable_js"
version = "0.1.0"
edition = "2021"

[dependencies]
tao = "0.32.0"
# wry = { path = "../../../wry" }
# wry = { git = "https://github.com/Simon-Laux/wry", branch = "disable-javascript" }
wry = { workspace = true }
