[package]
name = "wry_disable_js"
version = "0.1.0"
edition = "2021"

[dependencies]
tao = "0.32.0"
wry = { version = "0.49.0", git = "https://github.com/Simon-Laux/wry", branch = "disable-javascript" }
